[package]
name = "tw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httping = "0.1.8"
discord-webhook-lib = "0.1.4"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
config = "0.14.0"
anyhow = "1.0.80"
reqwest = "0.11.24"
chrono = "0.4.34"
Fasching = "0.1.15"
