### USB Monitor
usb_mon_enabled = "true"
reboot_on_increase_of_usb_devices = "false"
notify_on_increase_of_usb_devices = "false"
unmount_crypt_on_increase_of_usb_devices = "true"

### Burn File Monitor
burn_file_mon_enabled = "true"
unmount_crypt_on_file_burn = "true"
ssh_check_burn_host = "v1a"
ssh_check_burn_user = "root"
ssh_check_burn_key = "/home/foxx/.ssh/id_ed25519_012924"
ssh_check_burn_path = "/root/.cache/burn"
ssh_check_burn_check_interval = "30"
burn_path_1 = "/root/test/"
### Network Monitor
net_mon_enabled = "false"

######## Notification settings
discord_webhook_url = "https://discord.com/api/webhooks/1014319311197847593/jjY11oRqtES_FS7lz330mqi_4rSl-zA_rNvcg2yDySriqStqmuZtntLsF8dKY1sQvrEW"
discord_webhook_avatar_name = "Lazarus"
