### Enable Monitors
usb_mon_enabled = "true"
net_mon_enabled = "false"
## USB Monitor
reboot_on_increase_of_usb_devices = "false"
### UnMount Drives (cryptsetup+)
unmount_crypt_on_increase_of_usb_devices = "true"
umount_drives_1 = ""
### Check Burn File
ssh_check_burn_host = ""
ssh_check_burn_user = ""
ssh_check_burn_key = ""
ssh_check_burn_path = ""

######## Notification settings
discord_webhook_url = "https://discord.com/api/webhooks/1014319311197847593/jjY11oRqtES_FS7lz330mqi_4rSl-zA_rNvcg2yDySriqStqmuZtntLsF8dKY1sQvrEW"
discord_webhook_avatar_name = "Lazarus"
